language: node_js
node_js: '12'
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile --non-interactive

stages:
  - name: test
    if: (tag IS blank) OR (type != push)
  - name: deploy
    if: (tag IS present) AND (type = push)

jobs:
  include:
    - stage: test
      name: 'Test'
      script:
        - yarn
        - yarn build
        - yarn test

    - stage: deploy
      script:
        - yarn
        - yarn build